# docker-compose.yml
version: '3'

services:
  server:
    build: .
    container_name: server
    ports:
      - "5000:5000"
    command: ["python", "server.py"]

  client1:
    build: .
    container_name: client1
    depends_on:
      - server
    command: ["python", "client.py"]

  client2:
    build: .
    container_name: client2
    depends_on:
      - server
    command: ["python", "client.py"]

  client3:
    build: .
    container_name: client3
    depends_on:
      - server
    command: ["python", "client.py"]
